name: SCL
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.8
  - python=3.9.13
  - pip
  - pytorch=2.4.1
  - torchvision=0.19.1
  - numpy=1.26.4
  - matplotlib=3.9.2
  - scipy=1.13.1
  - tensorboard=2.17.1
  - pip:
    - tqdm
    - opencv-python
